# Generated by Django 5.0.14 on 2026-10-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('cast', models.CharField(help_text='Comma-separated cast names', max_length=400)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=80)),
            ],
        ),
    ]
