# Generated by Django 5.0.14 on 2026-10-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=80)),
                ('job_title', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
            ],
        ),
    ]
